#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace psvitaalive::ui {

enum class MascotSource {
    Internal = 0,
    User
};

struct MascotInfo {
    std::string key;       // internal:<id> or user:<id>
    std::string id;        // folder name
    std::string name;      // display name from mascot.json
    std::string basePath;  // folder containing mascot.json + PNG frames
    MascotSource source = MascotSource::Internal;
};

/**
 * Protection-screen mascot loader/runtime.
 *
 * - Scans app0:mascots/ and ux0:data/psvitaalive/mascots/.
 * - Keeps only lightweight metadata while the protector is inactive.
 * - Loads PNG textures only for the mascot used by the current protector session.
 * - Supports schema_version=1 generated by the PSVitaAlive web Mascot Generator.
 * - All public methods are expected to run on the main UI thread.
 */
class MascotManager {
public:
    MascotManager();
    ~MascotManager();

    MascotManager(const MascotManager&) = delete;
    MascotManager& operator=(const MascotManager&) = delete;

    /** Rescan built-in and user roots. Safe while no mascot session is active. */
    void scan();

    const std::vector<MascotInfo>& mascots() const;
    const MascotInfo* find(const std::string& key) const;

    /** Cycle Random -> Off -> discovered mascots -> Random. */
    std::string cycleSelection(const std::string& current, int delta) const;

    /**
     * Start one protector session. selection is "random", "off", or a source-qualified key.
     * Missing/invalid explicit selections fall back to another valid mascot when possible.
     */
    bool start(const std::string& selection, uint64_t nowMs);

    /** Stop session and release all current mascot textures. */
    void stop();

    void update(uint64_t nowMs);
    void render() const;

    bool active() const;
    const std::string& activeKey() const;

private:
    struct Impl;
    Impl* impl_ = nullptr;
};

} // namespace psvitaalive::ui
